### ISSUE TITLE
DEFAULT_PATH_LEAF_TO_NULL not parsing

### ISSUE THREAD

**Issue by redphare** [graphiq-data/pdi-fastjsoninput-plugin#10]
Using PDI 6.1

Followed your post, but the parsing is not working.
https://blog.graphiq.com/an-alternative-approach-to-reading-json-in-pentaho-s-data-integration-9e426dc098da#.xrzmnxjgs

> Fast JSON Input.0 - The data structure is not the same inside the resource! We found 56 values for json path [$..Inquiry], which is different that the number retourned for path [$..Name] (100 values). We MUST have the same number of values for all paths.

Any ideas? Thanks

**Comment by jadametz** [comment]
Thanks for the issue submission @redphare! We'll try and take a look soon to verify this issue. However it should be noted that Pentaho is currently working on implementing the Fast JSON Input step natively to Kettle 6.1 so you may look into their progress on that and use the native JSON parsing step.

**Comment by xtupan** [comment]
Hi @jadametz  for pdi-ce-5.4.0.1-130 version, the DEFAULT_PATH_LEAF_TO_NULL option is also not working. Do i miss something during the installation of the fastjson plugin? fastjson input is just working fine and i badly need the DEFAULT_PATH_LEAF_TO_NULL option for my project. hope you could address my concern. Thanks

**Comment by jadametz** [comment]
@xtupan could you send over some additional information?

- What does the JSON data that you're trying to parse look like?
- How is the JSON step configured?

Either screen shots or your attached data / transformations would be helpful.

**Comment by xtupan** [comment]
![aa](https://cloud.githubusercontent.com/assets/20190110/16491630/4b474482-3f11-11e6-8300-112e5c467c83.JPG)
as seen on the screenshot, objectId on the second object of meds doesn't exist and it should just leave as NULL when checking the DEFAULT_PATH_LEAF_TO_NULL option but i getting error with uneven number of values on objectid.

**Comment by jadametz** [comment]
Thanks for the info, @xtupan.

I recreated your data and parsed it myself and was able to get things to work.

![](https://s3.amazonaws.com/f.cl.ly/items/1i3M1d2w2V2y033e3R20/Image%202016-06-30%20at%209.42.11%20AM.png?v=f7c19dfc)

For your reference, [here is the data and transformation](http://cl.ly/gahe) I used to get these results.

**Comment by mr-gentleman** [comment]
I have a similar problem to the above users. And PDI did not integrate anything new in their 6.1 version.

Here is the data I'm trying to parse:

![question_json](https://cloud.githubusercontent.com/assets/20465691/16859039/419db8cc-49f1-11e6-9ae0-1e5b7846720f.PNG)

And I'm using fast JSON input to parse thusly:

![fast_json_input](https://cloud.githubusercontent.com/assets/20465691/16859044/4d871f70-49f1-11e6-9abb-acbfb6fb6f7d.PNG)

But I'm getting the following error message:

![pdi_error](https://cloud.githubusercontent.com/assets/20465691/16859049/53f2d4bc-49f1-11e6-8406-e13d2de7a793.PNG)

(it says custom_value instead of order but that was my original name for the field)

I have the default missing leafs to null option checked of course - doesn't appear to be working. What is the secret here? I've seen your code above --- but why exactly are 2-3 different JSON input steps necessary? Perhaps an explanation would be clearer. Thanks!
