### ISSUE TITLE
Issue while getting Nested JSON Data

### ISSUE THREAD

**Issue by lalgourav1983** [graphiq-data/pdi-fastjsoninput-plugin#7]
I was looking at issue reported by some one in forum and tries to find the resolution for it. I came to you about this plugin as it looks like to resolve the issue but when this plugin did not work when we have Nested JSON Data. I am attaching a transformation and file which i am using . I am able to get the data with this plugin but data is incorrect which i got as an output from the plugin

[FastJsonIssue.zip](https://github.com/graphiq-data/pdi-fastjsoninput-plugin/files/156451/FastJsonIssue.zip)

**Comment by jadametz** [comment]
Thanks for the issue submission, @lalgourav1983 

After taking a look through your transformation I believe I see the issue you're talking about but let me summarize to confirm.

Your data has 2 top level nodes. UID `1543567` and `21562314`. The first has a nested structure with multiple `identities`, one of of which has a value for `oldestDataUpdated` which all of the other nodes do not.

![](https://s3.amazonaws.com/f.cl.ly/items/2j0T1v3h2C472O0G0X3d/unstruct_js.png?v=9ae58cc4)

However, the output from FastJSON, once encountering this value continues to produce the value for the next node since the value is "undefined."

![](https://s3.amazonaws.com/f.cl.ly/items/43130h021g1J3w3I2J2e/Examine_preview_data_and_Spoon_-_Test_JSON__changed_.png?v=d0ae88e1)

The expected behavior is that the values in the `oldestDataUpdated` column would be: `null`, `2015-07-14T13:37:43.682Z`, `null`.

Does this all sound correct based on my understanding of your issue?

**Comment by jadametz** [comment]
After the fix:

![](https://s3.amazonaws.com/f.cl.ly/items/2l0C311X3B3T1N3f3Y2q/Image%202016-03-03%20at%2012.04.01%20PM.png?v=8d6674dc)

**Comment by lalgourav1983** [comment]
Thanks for the fix . I have tested it and it works fine. Appreciate your help on fixing it. Please update it on Marketplace as well.
